name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yaml

  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v5

      - name: Extract Version
        id: get-version
        run: |
          VERSION=$(grep -oP 'packageVersion = "\K[0-9]+\.[0-9]+\.[0-9]+' composeApp/build.gradle.kts)
          echo "Version found: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          name: Release ${{ env.version }}
          body: |
            Changelog for release ${{ env.version }}
          draft: true
          prerelease: false
          files: |
            artifacts/linux/*.deb
            artifacts/macos/*.dmg
            artifacts/windows/*.msi
  preview:
    concurrency:
      group: "live"
      cancel-in-progress: false
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.details_url }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ATTO_APPLICATION_LIVE }}
          channelId: preview

  deploy:
    concurrency:
      group: "live"
      cancel-in-progress: false
    environment:
      name: release
      url: ${{ steps.deploy.outputs.details_url }}
    runs-on: ubuntu-latest
    needs:
      - preview
    steps:
      - uses: actions/checkout@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ATTO_APPLICATION_LIVE }}
          channelId: live
